### ISSUE TITLE
random gradient is not working as expected

### ISSUE THREAD

**Issue by Nirbhayparmar** [gdsc-pdeu/gradientiser-BgGenerator#9]
**Describe the bug**
The generate random gradient button is not working as expected.

**To Reproduce**
1. Go to the site.
2. Click on the get random gradient button.
3. You will see that the gradient background is not generating, it stays yellow and red, although the colour picker is changing but the background is not changing.

**Expected behavior**
The get random random background button should generate the random background when ever it is clicked upon. And also there should be some default direction so it will work as expected.

**Comment by theprojectcode** [comment]
Hey, can I work on this?

**Comment by iamvaiibhav19** [comment]
@Nirbhayparmar I would like to work on this issue!!

**Comment by Nirbhayparmar** [comment]
thank you @ne0rad , your code solves the bug.
